version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27117:27017
    # volumes:
    #   - ./dockerfiles/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: pabron
      MONGO_INITDB_ROOT_PASSWORD: passw0rd

  mongo-perf:
    build:
      context: .
    volumes:
      - ./logs:/tmp/mongo-perf/logs
    command: >
      /bin/bash ./run.sh
